site_name: PHIS developper documentation
theme: bootstrap
extra_css:
   - "css/bootstrap.css"
   - "css/site.css"
   - "css/navbar.less"
pages:
   - Home: index.md
   - Using git: github.md
   - Local Installation: localInstallation.md
   - Coding Style: codingStyle.md
   - Functionality Validation: functionalityValidation.md
   - BrAPI Implementation: brapiImplementation.md
   - Webapp: webapp.md
